{
 "title": "Windows AIDA64 Hardware Statistics",
 "description": "Dashboard that uses AIDA64 to export all of your Windows (hardware) statistics to show temperatures, voltages, clock speed, cpu usage, disk utilisation and usage, memory speed and utilisation.\n\n",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(aida_sys_scpuuti, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aida_sys_scpuuti{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "aida_sys_scpucuti{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{core}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rpm" }
   ],
   "targets": [
    {
     "expr": "aida_fan{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{documentation}}"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "aida_volt{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{documentation}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "aida_temp{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{documentation}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aida_sys_memuti{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{documentation}}"
    }
   ]
  },
  {
   "title": "Disk Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "aida_temp_thdd{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{documentation}}"
    }
   ]
  }
 ]
}